# Generated by Django 5.1 on 2024-11-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_remove_record_city_remove_record_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='agent_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='agent_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='car_color',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='car_model',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='company_branch',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='plate_number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
